### PR TITLE
Fixed timestamp parsing Bug

### PR DESCRIPTION
**Pull request by flottokarotto**
If Sub_Second is less then 0.1, Constrained_Error will be raised. Using
Float'Floor solves the problem

### CODE REVIEW

**Comment by faelys** [comment]
Thanks a lot for the reporting of this very serious issue!

However, I'm a bit unsure about your analysis and your solution. From what I can tell, Constraint_Error is indeed raised in some cases, but not when Sub_Second is less than 0.1, but rather when it's above 0.95.

It seems the root the issue that Duration-to-Natural conversion is rounding instead of truncating, so that any digit followed by a digit greater or equal than 5 is incorrect. For example in my latest test, Duration'Image (Sub_Section) is "0.915285000", which is presumably the real value, while Frac is set to ".925395". So here 1, 2 and 8 turned respectively into 2, 3 and 9 because of rounding.

However, this is correct that this issue causes an exception only in the first digit, because the modulo operation causes the others to say withing array range.
Still, a correct solution would fix the rounding of all digits, not only the first one as in your commit.

Moreover, I'm not really fond of the idea of using floating point intermediate value. It seems wasteful to convert from fixed-point to floating-point to integer, I'm pretty sure something can be worked to involve only one conversion.

Still, thanks again for the report, I wonder how I missed it!

**Comment by flottokarotto** [comment]
You are right, my analysis is wrong. Thanks for your detailed analysis and advice.  
If i get a are more elegant / efficient idea to fix the issue i will let you know.

**Comment by faelys** [comment]
I think I found a more elegant and efficient fix, using the fact that for positive values, the standard definition of rounding yields a truncation by subtracting 0.5. So a special case had to be made for 0.0, which would incorrectly be "truncated" to -1, and I committed it in f618780

**Comment by faelys** [comment]
And I forgot to add, I checked that implementation by comparing it against GNAT's Duration'Image, and in a few tens of thousands of roughly random values of Sub_Second, all six digits matched perfectly.

The reason I'm not using Duration'Image in the code though is that I don't want to depend on the implementation-specific output of the function, even though I end up depending on Natural being able to store 6-digit numbers (so it doesn't work on platforms with 16-bit Naturals).

**Comment by flottokarotto** [comment]
Yours fix looks great,  much better then mine :) 
Thanks a lot.

**Pull request closed without merging**
